#  footprint of the tractor case_ih_7210_pro
footprint: [[-2.2, -1.2], [-2.2, 1.2], [2.2, 1.2], [2.2, -1.2]]
footprint_padding: 0.1
robot_base_frame: lizard_caterpillar_836k_landfill_eiffage_18/base_link
update_frequency: 6.0
publish_frequency: 4.0
transform_tolerance: 0.5

resolution: 0.05

# global filtering parameters that apply to all sensors
obstacle_range: 30.0
raytrace_range: 35.0
max_obstacle_height: 100
min_obstacle_height: -100


#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: false

obstacles_laser:
    observation_sources: laser
    laser: {
      topic: lizard_caterpillar_836k_landfill_eiffage_18/scan,
      data_type: LaserScan,
      clearing: true,
      marking: true,
      inf_is_valid: false
      }

inflation:
    inflation_radius: 0.50
