global_frame: map
static_map: true
track_unknown_space: true

plugins:
- {name: static,                  type: "costmap_2d::StaticLayer"}
- {name: inflation,               type: "costmap_2d::InflationLayer"}
- {name: rgbd_obstacle_layer,     type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
