#  footprint of the tractor case_ih_7210_pro
footprint:  [[-5.3,-3.2],[-5.3,3.2],[5.3,3.2],[5.3,-3.2]]
footprint_padding: 0.25
robot_base_frame: nmc_d_11_bulldozer_12/base_link  #lizard_caterpillar_836k_landfill_eiffage_12/base_link
update_frequency: 3.0 #6.0
publish_frequency: 2.0 #4.0
transform_tolerance: 0.25

resolution: 0.15

# global filtering parameters that apply to all sensors
obstacle_range: 30.0
raytrace_range: 40.0
max_obstacle_height: 100
min_obstacle_height: -100


#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: false

obstacles_laser:
    observation_sources: laser
    laser: {
      topic: nmc_d_11_bulldozer_12/scan,  #lizard_caterpillar_836k_landfill_eiffage_12/scan,
      data_type: LaserScan,
      clearing: true,
      marking: true,
      inf_is_valid: false
      }

inflation:
    inflation_radius: 3.50
