
global_frame: odom
rolling_window: true

plugins:
 - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
 # add inflation to make the costmap represent the configuration space of the robot.
 - {name: inflation,                 type: "costmap_2d::InflationLayer"}
